alerter/alerter.go
cleaner/cleaner.go
config/config.go
detector/detector.go
filter/filter.go
main.go
storage/admindb/cache.go
storage/admindb/db.go
storage/db.go
webapp/server.go

Logging: More detailed messages

---

config/config.go
config/config.json
filter/filter.go
main.go

Filter add limiter

---

config/config.go
config/config.json
filter/filter.go

Config: Move IntervalHitLimit to config.Detector

---

alerter/alerter.go
config/config.go
config/config.json
models/rule.go

Rule: Add DefaultTrustLines

---

config/config.go
config/config.json
config/errors.go
main.go

Config validation

---

.travis.yml

Add golint to travis-ci

---

filter/filter.go

Use atomic in Filter.go

---

cleaner/cleaner.go
config/config.go
detector/cursor/cursor.go
detector/cursor/cursor_test.go
detector/detector.go
models/state.go
storage/db.go
storage/statedb/db.go
storage/statedb/encoding.go

Detector: FillBlankZeros implementation

---

Makefile

Makefile: Add command changelog

---

filter/filter.go
filter/filter_test.go
main.go

Add TestHitLimit

---

static/package.json

Deps: Add missing koa-proxy

---

static/config/_base.js
static/package.json
static/src/components/AdminTable.js
static/src/redux/modules/project.js

Finished projects page

---

static/src/components/AdminTable.js
static/src/redux/modules/project.js

Fix error message display

---

.travis.yml
main.go
webapp/project.go
webapp/rule.go
webapp/user.go

sqlite3的写错误的捕捉有错误。因为要比较code而不是err本身

Errors: Fix sqlite3 errors handling

---

alerter/alerter.go
config/config.go
config/config.json
config/errors.go

Add oneDayLimit in alerter

---

static/src/components/Header.js
static/src/redux/modules/project.js

Lint errors fixes

---

models/rule.go
models/rule_test.go

Add test for rule.Test

---

static/public/index.html
static/public/package.json
static/src/app.js

@hit9  可以直接写angular-material 里面的指令什么的，我修改框架样式，不影响业务代码。

Add angular-material lib

---

static/Makefile
static/README.md

Use Makefile for deps installation

---

static/src/modules/admin/project/AdminProjectDetail.html
static/src/modules/admin/project/list.html
static/src/modules/layout/navigation.html

Rules page to meterial

---

static/src/modules/admin/project/AdminProjectDetailCtrl.js
static/src/modules/admin/project/RuleModalCtrl.js
static/src/modules/admin/project/list.html
static/src/modules/admin/project/projectModal.html
static/src/modules/admin/project/ruleModal.html

Use meterial ui for rules page

---

static/.jshintrc
static/gulpfile.js
static/src/modules/admin/project/AdminProjectDetailCtrl.js
static/src/modules/admin/project/AdminProjectListCtrl.js
static/src/modules/admin/project/ProjectModalCtrl.js
static/src/modules/admin/project/RuleModalCtrl.js
static/src/modules/admin/project/index.js
static/src/modules/layout/HeaderCtrl.js
static/src/modules/layout/NavigationCtrl.js
static/src/modules/layout/index.js
static/src/run.js
static/src/services/Project.js

Fix lint errors

---

static/src/modules/admin/project/AdminProjectDetail.html
static/src/modules/admin/project/AdminProjectDetailCtrl.js
static/src/modules/admin/project/AdminProjectListCtrl.js
static/src/modules/admin/project/ProjectModalCtrl.js
static/src/modules/admin/project/projectModal.html
static/src/services/Project.js

Finished edit project module

---

static/src/modules/admin/project/AdminProjectDetail.html

Use tabs instead of panels in project detail page

---

static/src/app.js
static/src/modules/admin/index.js
static/src/modules/admin/user/AdminUserList.html
static/src/modules/admin/user/AdminUserListCtrl.js
static/src/modules/admin/user/UserAddModalCtrl.js
static/src/modules/admin/user/userModal.html
static/src/modules/layout/navigation.html
static/src/services/User.js

@hit9 user新增失败，需要白天联调下看看为什么，页面逻辑做的差不多了。

Add Receiver page

---

webapp/user.go

Webapp: Fix createUser regexp and length validation

---

static/src/modules/admin/user/userModal.html

Phone should be string and init enableXXX to true

---

storage/admindb/db.go

Disable gorm log mode

---

static/src/modules/admin/config/AdminConfigCtrl.js
static/src/modules/admin/config/config.html
static/src/modules/admin/index.js
static/src/modules/layout/navigation.html
static/src/services/Config.js
static/src/services/index.js

Add admin/config implementation

---

webapp/user.go

@facesea 
给updateUser加上了validation..

Validate request on updateUser

---

webapp/api.md
webapp/server.go
webapp/user.go

@facesea 
新的接口:
```
GET /api/user/:id/projects
```
返回一个数组。

Add new interface getUserProjects

---

static/src/modules/admin/project/AdminProjectDetail.html
static/src/modules/admin/project/AdminProjectDetailCtrl.js
static/src/modules/admin/project/UserModalCtrl.js
static/src/modules/admin/project/userModal.html
static/src/modules/admin/user/AdminUserList.html
static/src/services/Project.js
static/src/services/User.js

	Finished add user page

---

webapp/errors.go
webapp/project.go

Validate duplicate user for project

---

filter/doc.go

Add doc.go for filter

---

webapp/errors.go
webapp/project.go

@facesea @nrzipher 
先dirty点的fix掉了。等gorm那边作者给个回复再说。。

Temp fix duplicate user to project by pre select

---

static/src/constants/AdminNavList.js
static/src/constants/index.js
static/src/modules/admin/project/AdminProjectDetailCtrl.js
static/src/modules/admin/user/AdminUserDetail.html
static/src/modules/admin/user/AdminUserDetailCtrl.js
static/src/modules/layout/HeaderCtrl.js
static/src/modules/layout/NavigationCtrl.js
static/src/modules/layout/header.html
static/src/modules/layout/index.less
static/src/modules/layout/navigation.html

	Add delete user function

---

static/src/modules/admin/project/AdminProjectDetail.html
static/src/modules/admin/project/AdminProjectDetailCtrl.js
static/src/modules/admin/project/UserModalCtrl.js
static/src/modules/admin/user/AdminUserDetail.html
static/src/modules/admin/user/AdminUserDetailCtrl.js
static/src/modules/layout/NavigationCtrl.js
static/src/modules/layout/navigation.html
webapp/server.go

Implement the deleteProject action

---

static/src/modules/admin/project/AdminProjectDetail.html
static/src/modules/admin/user/AdminUserDetail.html

Use $index+1 instead of id

---

static/src/modules/admin/project/AdminProjectDetail.html
static/src/modules/admin/project/AdminProjectDetailCtrl.js
static/src/modules/admin/project/UserModalCtrl.js
static/src/modules/admin/project/index.less
static/src/modules/admin/project/userModal.html

Update user list filter

---

static/src/modules/layout/index.less

Move footer higher

---

static/src/modules/admin/project/AdminProjectDetailCtrl.js
static/src/modules/admin/user/AdminUserDetailCtrl.js
static/src/run.js
static/src/services/httpInterceptor.js

	Add request interceptor when method is GET

---

.gitignore
detector/detector.go
storage/admindb/cache.go
storage/admindb/cache_test.go

Fix admindb cache init add the same rules

---

alerter/alerter.go
detector/detector.go
main.go
models/metric.go

Bind MatchedRules in detector, remove filter in alerter

---

detector/detector.go

Refuse name too long metrics in detector

---

alerter/alerter.go
detector/detector.go
models/metric.go

Test rules in detector instead of alerter

---

alerter/alerter.go
detector/detector.go

Fix call of reflect.Value.Type on zero Value

---

static/.jshintrc
static/src/modules/main/MainListCtrl.js

Static: Fix lint errors

---

alerter/alerter.go
static/.jshintrc
static/src/modules/main/MainListCtrl.js

Add metric.TestedTules

---

static/src/constants/DateTimes.js
static/src/modules/admin/project/AdminProjectDetail.html
static/src/modules/admin/project/AdminProjectDetailCtrl.js
static/src/modules/admin/project/list.html
static/src/modules/main/MainListCtrl.js
static/src/modules/main/index.less

Fixed some bug

---

static/src/modules/main/MainListCtrl.js

Remove useless uri param `type`

---

static/src/modules/admin/project/ruleModal.html
static/src/modules/main/MainListCtrl.js

	Fixed input change dont have projectId

---

static/src/modules/main/MainListCtrl.js
static/src/modules/main/chart.js
static/src/modules/main/index.less
static/src/modules/main/list.html

	Add scroll bar

---

static/src/modules/main/MainListCtrl.js
static/src/modules/main/chart.js

	Lock title refresh when normal

---

static/src/modules/admin/project/AdminProjectDetail.html
static/src/modules/common/common.less
static/src/modules/main/MainListCtrl.js
static/src/modules/main/index.less
static/src/modules/main/list.html

	Update th width

---

detector/cursor/cursor_test.go

Add 2 new test cases for cursor

---

alerter/alerter.go

Don't alert for the first time

---

static/src/modules/layout/HeaderCtrl.js
static/src/modules/layout/header.html

	Update Header link reload method

---

detector/detector.go
models/metric.go
models/rule.go
models/rule_test.go

Test with index.Score for trend related conditions

---

static/src/modules/main/MainListCtrl.js

Fix sort tab values

---

alerter/alerter.go
detector/detector.go
health/health.go
main.go
webapp/doc.go
webapp/info.go

https://github.com/eleme/banshee/issues/215
@nrzipher

Add health stats aggregator

---

static/src/constants/AdminNavList.js
static/src/constants/DateTimes.js
static/src/modules/admin/index.js
static/src/modules/admin/info/AdminInfoCtrl.js
static/src/modules/admin/info/info.html
static/src/services/Info.js
static/src/services/index.js

Add new nav info

---

detector/detector.go

https://github.com/eleme/banshee/issues/344

Experimental async fetching values for detector

---

alerter/alerter.go
models/rule.go
static/src/modules/admin/project/AdminProjectDetail.html
static/src/modules/admin/project/AdminProjectDetailCtrl.js
static/src/modules/admin/project/RuleModalCtrl.js
static/src/modules/admin/project/ruleModal.html
static/src/services/Rule.js
webapp/errors.go
webapp/rule.go
webapp/server.go

Known issue:
TrendUp and TrendDown won't reflect real values when editing rules.

Add rule editor

---

static/src/modules/admin/project/AdminProjectDetailCtrl.js
static/src/modules/admin/project/RuleModalCtrl.js
static/src/modules/admin/project/ruleModal.html

Fix default values on editRule modal

---

alerter/alerter.go
config/config.go
config/doc.go
config/errors.go
config/exampleConfig.json
models/project.go
models/validation.go
models/validation_test.go
static/src/modules/admin/project/AdminProjectDetail.html
static/src/modules/admin/project/AdminProjectDetailCtrl.js
static/src/modules/admin/project/ProjectModalCtrl.js
static/src/modules/admin/project/projectModal.html
webapp/project.go

Issue #377, requested by @ritksm .
Summary:
1. Implement alerting silence for project.
2. Use default silent range (by default: 00:00~06:00) if the project disabled the silence.

Implement alerting silence for project.

---

cleaner/cleaner.go

Log debug on cleaning outdated metrics

---

models/rule.go
models/rule_test.go
static/src/modules/admin/project/AdminProjectDetail.html
static/src/modules/admin/project/AdminProjectDetailCtrl.js
webapp/project.go
webapp/rule.go

Fix https://github.com/eleme/banshee/issues/397

Move buildRepr to static end

---

static/src/modules/admin/project/RuleModalCtrl.js
static/src/modules/admin/project/ruleModal.html

Fix rule edit modal title

---

static/src/modules/admin/project/AdminProjectListCtrl.js
static/src/modules/admin/project/index.less
static/src/modules/admin/project/list.html
static/src/modules/admin/user/AdminUserList.html
static/src/modules/admin/user/AdminUserListCtrl.js
static/src/modules/admin/user/index.less

add search function

---

static/src/modules/admin/project/AdminProjectListCtrl.js
static/src/modules/admin/user/AdminUserListCtrl.js

@hit9 原因是autocomplete onchange的时候立马跳转它的遮罩层没有及时关掉，我看文档也没有比onchange更好的绑定时机，所以需要用$timeout延时执行，这是material自身没考虑到这种情况。

Fixed can't click after search

---

static/src/modules/admin/project/AdminProjectListCtrl.js

Fix syntax error

---

models/rule_test.go

Result on may air (4 Core):
```
BenchmarkRuleTest-4                             10000000               142 ns/op
BenchmarkRuleTestWithDefaultThresholdMaxsNum4-4  3000000               576 ns/op
BenchmarkRuleTestWithDefaultThresholdMaxsNum8-4  2000000               713 ns/op
```

Add benchmark for rule.Test

---

alerter/alerter.go

For: tracking event with id
#428 
@wooparadog

Add event ID by metricName and Stamp

---

models/rule.go

Thanks for @wooparadog reporting this.

Fix cached rule.Comment empty bug

---

static/.jshintrc
static/src/filters/index.js
static/src/modules/main/MainListCtrl.js
static/src/modules/main/index.less

@hit9 ,你先看看样式行不行，如果行就合掉，需要修改的话微信我，我会带电脑的。

Add rules select which link to project page

---

static/src/modules/admin/project/AdminProjectDetailCtrl.js
static/src/modules/main/MainListCtrl.js

@facesea 在你的PR的基础上，给project页面加了个url参数`rule`, 首页链过来的找规则的会直接打开edit rule modal.

Add url query `rule` to load edit rule modal on load

---

webapp/project.go

https://github.com/eleme/banshee/issues/438

Delete related rules and user relationships on project detected.

---

webapp/user.go

Remove user:proj relationships on user deteted

---

models/rule.go
models/rule_test.go

Fix bug#456: Test defaultThresholds only if trendX and no rule threshold

---

storage/metricdb/db.go

Cause: https://github.com/syndtr/goleveldb/issues/93

Try to disable the block cache.

---

storage/metricdb/db.go

Revert "Try to disable the block cache."

---

alerter/alerter.go

Execute alerter command with timout 5 secs

---

detector/detector.go
detector/detector_test.go

Bug fix #470: Only fill zeros if the values not empty and the first

---

storage/metricdb/db.go
storage/metricdb/db_test.go

Don't expire metric storage by given stamp but expire by pool

---

README.md
changelog
detector/detector.go

future data should not fill zero

---

deploy.py

https://github.com/eleme/banshee/issues/554

Don't deploy binary if the only_static is set

---

alerter/alerter.go
detector/detector.go

Add more log in detector and alerter

---

filter/filter.go
filter/filter_test.go

reset rule hits by stamp of metric

---

docs/web-api.md
storage/eventdb/db.go
storage/eventdb/db_test.go
webapp/errors.go
webapp/event.go
webapp/server.go

Add web api to get events by time range

---

filter/filter.go
models/rule.go

Remove rule unique constraint

---

alerter/notifier/slack.go
detector/detector.go

Ignore too long nama metric

---

detector/detector.go
filter/filter.go
filter/filter_test.go
webapp/metric.go

about https://github.com/eleme/banshee/issues/623

Ignore rule hit limit when look up rules from webapp

---

config/errors.go

tiny aesthetic fixes to error strings

tiny improvemnts to error strings

---

storage/metricdb/db.go

Fix forgot to release iterator in early returns

---

alerter/alerter.go

Fix silent bug

---

alerter/notifier/encoding.go

Fix notice bug
